import { supabase } from '../lib/supabase';
import type { ImportPreview, ImportResult, ImportHistoryItem, TradeRead } from './types';

function escapeCsv(val: unknown): string {
  const s = val == null ? '' : String(val);
  if (s.includes(',') || s.includes('"') || s.includes('\n')) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function generateCsv(trades: TradeRead[], fields: string[]): string {
  const header = fields.join(',');
  const rows = trades.map((t) =>
    fields.map((f) => escapeCsv((t as any)[f])).join(',')
  );
  return [header, ...rows].join('\n');
}

function generateHtmlReport(trades: TradeRead[], projectName?: string): string {
  const wins = trades.filter((t) => t.result === 'WIN').length;
  const losses = trades.filter((t) => t.result === 'LOSS').length;
  const totalPnl = trades.reduce((sum, t) => sum + (t.pnl ?? 0), 0);
  const avgRR = trades.length > 0 ? trades.reduce((sum, t) => sum + (t.rr ?? 0), 0) / trades.length : 0;
  const winRate = trades.length > 0 ? ((wins / trades.length) * 100).toFixed(1) : '0';

  const rows = trades.map((t) => `
    <tr>
      <td>${t.pair || '-'}</td>
      <td>${t.direction || '-'}</td>
      <td>${t.result || '-'}</td>
      <td>${t.pnl != null ? `$${t.pnl.toFixed(2)}` : '-'}</td>
      <td>${t.rr?.toFixed(2) ?? '-'}</td>
      <td>${t.entry_price?.toFixed(5) ?? '-'}</td>
      <td>${t.exit_price?.toFixed(5) ?? '-'}</td>
      <td>${t.open_time ? new Date(t.open_time).toLocaleDateString() : '-'}</td>
    </tr>
  `).join('');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Trade Report</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #333; padding: 40px; }
h1 { font-size: 24px; margin-bottom: 4px; }
.subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
.stats { display: flex; gap: 24px; margin-bottom: 32px; }
.stat { background: #f5f5f5; border-radius: 8px; padding: 12px 20px; }
.stat-label { font-size: 11px; text-transform: uppercase; color: #888; }
.stat-value { font-size: 20px; font-weight: 700; margin-top: 4px; }
table { width: 100%; border-collapse: collapse; font-size: 12px; }
th { text-align: left; padding: 8px 12px; background: #f5f5f5; border-bottom: 2px solid #ddd; font-weight: 600; }
td { padding: 8px 12px; border-bottom: 1px solid #eee; }
tr:hover { background: #fafafa; }
.footer { margin-top: 32px; font-size: 11px; color: #999; text-align: center; }
</style></head>
<body>
  <h1>Trading Report</h1>
  <p class="subtitle">${projectName || 'Project'} &mdash; ${trades.length} trades</p>
  <div class="stats">
    <div class="stat"><div class="stat-label">Total P&L</div><div class="stat-value">${totalPnl >= 0 ? '+' : ''}$${totalPnl.toFixed(2)}</div></div>
    <div class="stat"><div class="stat-label">Win Rate</div><div class="stat-value">${winRate}%</div></div>
    <div class="stat"><div class="stat-label">Avg R:R</div><div class="stat-value">${avgRR.toFixed(2)}</div></div>
    <div class="stat"><div class="stat-label">W / L</div><div class="stat-value">${wins}W / ${losses}L</div></div>
  </div>
  <table><thead><tr>
    <th>Pair</th><th>Dir</th><th>Result</th><th>P&L</th><th>R:R</th><th>Entry</th><th>Exit</th><th>Date</th>
  </tr></thead><tbody>${rows}</tbody></table>
  <div class="footer">Generated by Minore Trading Journal</div>
</body></html>`;
}

export const tradeImportExportService = {
  previewImport: async (_projectId: string, _file: File): Promise<ImportPreview> => {
    throw new Error('Import preview requires Edge Function deployment');
  },

  confirmImport: async (_projectId: string, _importId: string, _duplicateStrategy: string = 'skip'): Promise<ImportResult> => {
    throw new Error('Import confirmation requires Edge Function deployment');
  },

  exportTrades: async (projectId: string, format: string, params?: Record<string, any>): Promise<Blob> => {
    let query = supabase.from('trade').select('*').eq('project_id', projectId).is('deleted_at', null);

    if (params?.ids?.length) query = query.in('id', params.ids);
    if (params?.date_from) query = query.gte('open_time', params.date_from);
    if (params?.date_to) query = query.lte('open_time', params.date_to);
    if (params?.symbol) query = query.ilike('pair', `%${params.symbol}%`);
    if (params?.result) query = query.eq('result', params.result);
    if (params?.status) query = query.eq('status', params.status);
    if (params?.strategy_id) query = query.eq('strategy_id', params.strategy_id);

    const { data, error } = await query;
    if (error) throw error;
    const trades = (data ?? []) as TradeRead[];

    const fields = ['pair', 'direction', 'result', 'pnl', 'rr', 'entry_price', 'exit_price', 'stop_loss', 'take_profit', 'position_size', 'risk_percent', 'open_time', 'close_time', 'notes', 'emotion', 'weekly_bias', 'daily_bias', 'h4_bias', 'liquidity_sweep', 'bos', 'mss', 'order_block', 'fvg'];

    switch (format) {
      case 'csv':
        return new Blob([generateCsv(trades, fields)], { type: 'text/csv;charset=utf-8;' });

      case 'json':
        return new Blob([JSON.stringify(trades, null, 2)], { type: 'application/json;charset=utf-8;' });

      case 'xlsx': {
        const csvData = generateCsv(trades, fields);
        const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head><meta charset="UTF-8"><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>Trades</x:Name></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head>
<body><table>${csvData.split('\n').map((row) => `<tr>${row.split(',').map((cell) => `<td>${cell}</td>`).join('')}</tr>`).join('')}</table></body></html>`;
        return new Blob([html], { type: 'application/vnd.ms-excel;charset=utf-8' });
      }

      case 'pdf': {
        const html = generateHtmlReport(trades, params?.project_name);
        return new Blob([html], { type: 'text/html;charset=utf-8;' });
      }

      default:
        return new Blob([generateCsv(trades, fields)], { type: 'text/csv;charset=utf-8;' });
    }
  },

  openPdfReport: async (projectId: string, params?: Record<string, any>): Promise<void> => {
    const blob = await tradeImportExportService.exportTrades(projectId, 'pdf', params);
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    setTimeout(() => URL.revokeObjectURL(url), 60000);
  },

  importHistory: async (projectId: string): Promise<ImportHistoryItem[]> => {
    const { data, error } = await supabase.from('trade_import').select('*').eq('project_id', projectId).order('created_at', { ascending: false });
    if (error) throw error;
    return (data ?? []) as ImportHistoryItem[];
  },
};
