
"""initial_baseline

Revision ID: 46e1ad79d1fb
Revises: 
Create Date: 2026-07-14 14:34:10.856034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '46e1ad79d1fb'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('conceptual_term', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflict',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('conflict_classification', sa.String(), nullable=True),
    sa.Column('contextual_applicability_check', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('admissibility_status', sa.String(), nullable=True),
    sa.Column('origin_type', sa.String(), nullable=True),
    sa.Column('attribution', sa.String(), nullable=True),
    sa.Column('temporal_reference', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('provenance_confidence', sa.String(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('verbatim_text', sa.String(), nullable=True),
    sa.Column('source_location', sa.String(), nullable=True),
    sa.Column('semantic_classification', sa.String(), nullable=True),
    sa.Column('paraphrase_representation', sa.String(), nullable=True),
    sa.Column('contextual_boundary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interpretation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.Column('interpretation_statement', sa.String(), nullable=True),
    sa.Column('reasoning_chain', sa.String(), nullable=True),
    sa.Column('interpretation_foundation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('conflict_id', sa.UUID(), nullable=False),
    sa.Column('question_statement', sa.String(), nullable=True),
    sa.Column('inquiry_origin', sa.String(), nullable=True),
    sa.Column('domain_relevance', sa.String(), nullable=True),
    sa.Column('substantive_grounding', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflict.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('association_state', sa.String(), nullable=True),
    sa.Column('ambiguity_metric', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_conflict',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('conflict_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflict.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypothesis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('research_question_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_statement', sa.String(), nullable=True),
    sa.Column('variable_specification', sa.String(), nullable=True),
    sa.Column('measurement_specification', sa.String(), nullable=True),
    sa.Column('substantive_departure', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_question_id'], ['research_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconsideration_trigger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('interpretation_id', sa.UUID(), nullable=False),
    sa.Column('trigger_detail', sa.String(), nullable=True),
    sa.Column('trigger_classification', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['interpretation_id'], ['interpretation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconsideration_trigger')
    op.drop_table('hypothesis')
    op.drop_table('claim_conflict')
    op.drop_table('association')
    op.drop_table('research_question')
    op.drop_table('interpretation')
    op.drop_table('claim')
    op.drop_table('source')
    op.drop_table('conflict')
    op.drop_table('concept')
    op.drop_table('project')
    # ### end Alembic commands ###
